name: 'Open Balena CLI'
branding:
  color: "yellow"
  icon: "upload-cloud"
description: 'Continuously deliver your IoT applications to BalenaCloud'
inputs:
  application_path:
    description: "Optional. Provide a subfolder path to your BalenaCloud application, example: ./balena-wpe"
    required: false
    default: "."
  balena_api_token:
    description: 'BalenaCloud API Key'
    required: true
  balena_command:
    description: "The command to execute with balena"
    required: true
  open_balena_address:
    description: "Provide address of intance for your OpenBalena cloud"
    required: true
  root_cert:
    description: "Provide content of your root cert for your OpenBalena cloud"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.balena_command }}
